---
title: "cs-01"
---









## Case Study 1: Critiquing Visualizations 
### Background 
Your first weekly project requires you to **submit** a review of 4-5 different data visualizations used to answer specific questions.  Some fun websites are [pudding.cool](https://pudding.cool/){target="blank"}, [wonkblog](https://www.washingtonpost.com/news/wonk/?utm_term=.c10a343a7262){target="blank"}, [fivethiryeight](https://fivethirtyeight.com/){target="blank"}, and [priceonomics](https://priceonomics.com/){target="blank"} (but you can use any website, blog, or article with a good visualization).


 * [Course Website](../index.html)






### Reading

This reading will help you complete the tasks below.

* o [Making your first R Markdown File](../rmarkdown_help.html){target='blank'}
* o [Chapter 27: R for Data Science - R Markdown](http://r4ds.had.co.nz/r-markdown.html){target='blank'}
* o [Chapter 30: R for Data Science - R Markdown workflow](http://r4ds.had.co.nz/r-markdown-workflow.html){target='blank'}


### Tasks


<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>


* [ ] Find 4-5 examples of data-driven answers and write a one-paragraph review of each.
    * [ ] List 2-3 items that are unique/good
    * [ ] Identify 1 issue with each example
* [ ] Create an `.Rmd` file in R-Studio
    * [ ] Title it Case Study 1 in the YAML
    * [ ] Include links or embedded images to the visualization post you found
    * [ ] Write a one paragraph critique of each visualization
    * [ ] Add the R code below to your `.Rmd` file
    * [ ] Knit the file to `.html` and keep the `.md` file as well
* [ ] Upload your `.md` and `.html` files to the intern development channel in our Slack group





### Code Snippet



```r
plot(1:20)
```


