---
title: "cs-12"
---






## Case Study 12: Keep your project moving 
### Background 

This week we will learn new coding techniques and visualization principles.  However, your case study  will provide time to makes sure you have the [semester project](https://byuistats.github.io/M335/project.html) completed.

 * [Course Website](../index.html)






### Reading

This reading will help you complete the tasks below.

* o [Semester Project](https://byuistats.github.io/M335/project.html){target='blank'}


### Tasks


<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>


* [ ] Finalize first draft of your project analysis
    * [ ] Choose your flavor of `.Rmd` for your presentation
    * [ ] Build a stand-alone analysis that helps a reader answer the question at hand with that available data
* [ ] Present your visualization based analysis that addresses your question
    * [ ] Present your analysis to your roommates (or spouse) and update your presentation based on the feedback
    * [ ] Get feedback from 2-3 fellow classmates on your presentation and update it based on their feedback
    * [ ] Present your draft presentation to a data scientist to review for clarity
    * [ ] Present your work in class, at a society meeting, the research and creative works conference, or as a blog post online









