---
title: "Class Discussion Materials"
---










## Weeks 1 & 2:  Introduction to R and Data Science

* **1/8 (Day 1):** [html](https://byuistats.github.io/M335/presentations_class/day_1.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_1.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_1.Rmd) 
* **1/13 (Day 2):** [html](https://byuistats.github.io/M335/presentations_class/day_2.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_2.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_2.Rmd) 
* **1/15 (Day 3):** [html](https://byuistats.github.io/M335/presentations_class/day_3.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_3.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_3.Rmd) 
* **1/22 (Day 4):** [html](https://byuistats.github.io/M335/presentations_class/day_4.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_4.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_4.Rmd) 

## Weeks 3 & 4: Programming in the Tidyverse

* **1/27 (Day 5):** [html](https://byuistats.github.io/M335/presentations_class/day_5.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_5.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_5.Rmd) 
* **1/29 (Day 6):** [html](https://byuistats.github.io/M335/presentations_class/day_6.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_6.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_6.Rmd) 
* **2/3 (Day 7):** [html](https://byuistats.github.io/M335/presentations_class/day_7.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_7.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_7.Rmd) 
* **2/5 (Day 8):** [html](https://byuistats.github.io/M335/presentations_class/day_8.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_8.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_8.Rmd) 

## Week 5: Handling Varied Data Types

* **2/10 (Day 9):** [html](https://byuistats.github.io/M335/presentations_class/day_9.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_9.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_9.Rmd) 
* **2/12 (Day 10):** [html](https://byuistats.github.io/M335/presentations_class/day_10.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_10.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_10.Rmd) 


## Week 6 & 7: Characters and RegEx

* **2/18 (Day 11):** [html](https://byuistats.github.io/M335/presentations_class/day_11.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_11.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_11.Rmd) 
* **2/19 (Day 12):** [html](https://byuistats.github.io/M335/presentations_class/day_12.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_12.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_12.Rmd) 
* **2/24 (Day 13):** [html](https://byuistats.github.io/M335/presentations_class/day_13.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_13.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_13.Rmd) 
* **2/26 (Day 14):** [html](https://byuistats.github.io/M335/presentations_class/day_14.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_14.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_14.Rmd) 

## Week 8 & 9: Dates and Time

* **3/2 (Day 15):** [html](https://byuistats.github.io/M335/presentations_class/day_15.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_15.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_15.Rmd) 
* **3/4 (Day 16):** [html](https://byuistats.github.io/M335/presentations_class/day_16.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_16.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_16.Rmd) 
* **3/9 (Day 17):** [html](https://byuistats.github.io/M335/presentations_class/day_17.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_17.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_17.Rmd) 
* **3/11 (Day 18):** [html](https://byuistats.github.io/M335/presentations_class/day_18.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_18.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_18.Rmd) 

## Week 10 & 11: Spatial

* **3/23 (Day 19):** [html](https://byuistats.github.io/M335/presentations_class/day_19.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_19.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_19.Rmd) 
* **3/25 (Day 20):** [html](https://byuistats.github.io/M335/presentations_class/day_20.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_20.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_20.Rmd) 
* **3/30 (Day 21):** [html](https://byuistats.github.io/M335/presentations_class/day_21.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_21.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_21.Rmd) 
* **3/18 (Day 22):** [html](https://byuistats.github.io/M335/presentations_class/day_22.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_22.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_22.Rmd) 

## Week 12 & 13: Finishing (Project and Semester Deliverables)

* **3/18 (Day 23):** [html](https://byuistats.github.io/M335/presentations_class/day_23.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_23.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_23.Rmd) 
* **4/1 (Day 24):** [html](https://byuistats.github.io/M335/presentations_class/day_24.html){target="blank"} / [md](https://byuistats.github.io/M335/presentations_class/day_24.md) / [rmd](https://byuistats.github.io/M335/presentations_class/day_24.Rmd) 
* **NA/NA (Day 25):** [html](NA){target="blank"} / [md](NA) / [rmd](NA) 
* **NA/NA (Day 26):** [html](NA){target="blank"} / [md](NA) / [rmd](NA) 


## Random Stuff

* [Spatial Class](spatial_class.html)
* [hathaway restaurant code](https://byuistats.github.io/M335/presentations_class/restaurants_idaho.html)
* [temple data sealing activity](temple_sealings.html)
* [Overview of Git and GitHub use in our course](git_335.html).  Please note the folder structure you need in your repository.
* [ggplot2 intro](https://stats.idre.ucla.edu/r/seminars/ggplot2_intro/): It has a nice example for `stat_summary()`
* [git command workflow](https://byuistats.github.io/M335/images/Git_workflow_diagram.png){target="blank"}
* [Data is Beautiful](https://np.reddit.com/r/dataisbeautiful/){target="blank"}
* [Zipcode Shape Files](https://www.census.gov/geo/maps-data/data/cbf/cbf_zcta.html)
