---
title: "task-03"
---









## Task 3:  Asking the right questions 
### Background 
Learning how to ask interesting questions takes time.  As data scientists we need to learn how to ask questions that data can answer.  [This task supports your final class project](https://byuistats.github.io/M335/project.html). **Note that the reading on data transformation below is necessary for the case study for this week and may be the most important reading of the semester to fully understand**


 * [Course Website](../index.html)




<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>


### Reading

This reading will help you complete the tasks below.

* o [Computational Thinking](https://www.edutopia.org/blog/computational-thinking-across-the-curriculum-eli-sheldon){target='blank'}
* o [Optional Reading for new programmers](https://jscomplete.com/learn/pro-programmer/beginner-programmers-mistakes){target='blank'}
* o [Creating Questions for your project (watch the videos that are free)](https://www.lynda.com/Business-Skills-tutorials/Harness-power-questions/477451/574315-4.html){target='blank'}
* o [Chapter 5: R for Data Science - Data transformation](http://r4ds.had.co.nz/transform.html){target='blank'}


### Tasks


* [ ] Take notes on your reading of the specified 'R for Data Science' chapter in a '.R' script or '.md' file.
* [ ] Develop a few novel questions that data can answer
    * [ ] Get feedback from 5-10 people on their interest in your questions and summarize this feedback
    * [ ] Find other examples of people addressing your question
    * [ ] Present your question in our slack channel to get feedback from one of the full-time data scientists on the quality of the question and if it can be addressed in 2-months.
* [ ] Create one `.rmd` file that has your report
    * [ ] Have a section for each question
    * [ ] Knit your `.rmd` file and post the resulting `.html` file to slack for feedback


------

**Additional Information**
   
* [Hadley dplyr motivation](http://datascience.la/hadley-wickham-presents-dplyr-at-user-2014/){target="blank"}   
* [Hadley Introduces dplyr](http://datascience.la/hadley-wickhams-dplyr-tutorial-at-user-2014-part-1/){target="blank"}   
* [Hadley dplyr part 2](https://www.youtube.com/watch?v=Ue08LVuk790&t=0s){target="blank"}   


