---
title: "task-01"
---









## Task 1: Understanding Graphical Perception, R, and R-Studio Setup 
### Background 
To create graphics that clearly answer questions, you must understand the basics of how the human perceptual system works. [This 40-minute talk by John Rauser](https://youtu.be/fSgEeI2Xpdc){target="blank"}, a data scientist in the technology industry, will give you an overview. You can find the code for the majority of his graphics [here](https://github.com/jrauser/writing/blob/master/how_humans_see_data/hhsd_notes.Rmd){target="blank"}.

You will also be responsible for getting R and Rstudio installed and running.


 * [Back](javascript:window.history.back();) or [Course Website](../index.html)




<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>


### Reading

This reading will help you complete the tasks below.

* o [John Rauser Talk](https://youtu.be/fSgEeI2Xpdc){target='blank'}
* o [Being a better online reader](https://www.newyorker.com/science/maria-konnikova/being-a-better-online-reader){target='blank'}
* o [Chapter 1:  R for Data Scientists](http://r4ds.had.co.nz/index.html){target='blank'}
* o [Getting used to R, Rstudio, and R Markdown (R basics)](https://rbasics.netlify.com/index.html){target='blank'}
* o [R and R-Studio Practice](https://byuistats.github.io/M335/rpages.html){target='blank'}


### Tasks


* [ ] Get R and R-Studio running on your computer
    * [ ] Fix your settings in R-Studio to use the [code diagnostics](https://support.rstudio.com/hc/en-us/articles/205753617-Code-Diagnostics)
* [ ] Watch John Rauser Presentation
    * [ ] Post in the Intern Development Slack Space your three favorite segments from the video and explain why you liked them.


