---
title: "task-04"
---










## Task 4:  Let's git going 
### Background 
You have just been hired to a new data science team, and you need to collaborate on projects.  The team lead told you to connect to your git repository on Github and edit the `README.md` in your repository. She wants you to describe who you are in a short paragraph.


 * [Course Website](../index.html)




<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>


### Reading

This reading will help you complete the tasks below.

* o [MCS 335, Git, and Github use](https://byuistats.github.io/M335/git_335.html){target='blank'}
* o [Why Git, Git, and GitHub setup (optional)](https://cfss.uchicago.edu/setup/what-is-git/){target='blank'}
* o [Getting Github and Git connected to R-Studio (optional)](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN){target='blank'}
* o [Chapter 8: R for Data Science - Projects (optional)](http://r4ds.had.co.nz/workflow-projects.html){target='blank'}
* o [R-Studio and the Git GUI (optional)](https://www.youtube.com/watch?v=E2d91v1Twcc){target='blank'}


### Tasks


* [ ] Install git on your computer
* [ ] Make sure your GitHub account is registered
* [ ] Work through readings on git and github
* [ ] Make sure git works in R-Studio
* [ ] Update your README.md in your repository (you will need to give me time to create your repo after you post your username)
    * [ ] Type one or two sentences that describe you
    * [ ] Make sure you pull and push
* [ ] Get your previous class tasks and case studies into the appropriate folders and add, commit, push with git


-------

**Additional Links**

* o [Chapter 4: Happy Git and Github for the useR - Installation](http://happygitwithr.com/installation-pain.html){target="blank"}
* o [Chapter 5: Happy Git and Github for the useR - GitHub](http://happygitwithr.com/github-acct.html){target="blank"}
* o [Chapter 7: Happy Git and Github for the useR - Install Git](http://happygitwithr.com/install-git.html){target="blank"}
* o [Chapter 8: Happy Git and Github for the useR - Using Git](http://happygitwithr.com/hello-git.html){target="blank"}
* o [Chapter 10: Happy Git and Github for the useR - Version Control](http://happygitwithr.com/push-pull-github.html){target="blank"}
* o [git](http://nyuccl.org/pages/GitTutorial/){target="blank"}
* o [githug](https://github.com/jennybc/githug){target="blank"}
* o [Git for R users](http://haven.tidyverse.org/){target="blank"}
* o [Getting Ready](https://byui-cs.github.io/CS246/week-04/prepare.html){target="blank"}
* o [Intro Tutorial](https://try.github.io/levels/1/challenges/1){target="blank"}
* o [Advanced Tutorial](http://learngitbranching.js.org/){target="blank"}

