---
title: "task-23"
---









## Task 23: Should we do it? 
### Background 

This week we will learn new coding techniques and visualization principles. Go back to task 11 and build your code into two or three **functions** that performs the same work for the tasks.  

1. Your functions can allow the input of the spacing between characters or maybe a vector that picks of specific characters.
2. Your functions could remove letters after periods and put the sentence into one string.
2. Your function can allow the input of specific grep commands.

 * [Course Website](../index.html)




<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>


### Reading

This reading will help you complete the tasks below.

* o [Chapter 29: R for Data Science - R Markdown format](http://r4ds.had.co.nz/r-markdown-formats.html){target='blank'}
* o [Chapter 19: R for Data Science - Functions](http://r4ds.had.co.nz/functions.html){target='blank'}


### Tasks


* [ ] Take notes on your reading of the specified 'R for Data Science' chapter in the README.md or in a '.R' script in the class task folder
* [ ] Repeat the [task 11 tasks](https://byuistats.github.io/M335/class_tasks/task11_details.html){target="blank"} using three functions that you built


